packages:
- '.'
# - '../profunctor-hep.git/'
- location:
    git: https://github.com/cspollard/profunctor-hep.git
    commit: 19e3f16af2b675215b9688d98de2ad4df4a0f068
  extra-dep: true

extra-deps:
- extensible-0.5.1
- membership-0

flags: {}
extra-package-dbs: []
resolver: lts-13.25
